### ISSUE TITLE
PPI data out of range subscript error

### ISSUE THREAD

**Issue by Lyn16** [netZoo/netZooM#139]
[ppi_GSE39612.txt](https://github.com/netZoo/netZooM/files/7960625/ppi_GSE39612.txt)
Hi, I am using Matlab to build panda network for a GEO cancer data. I keep seeing the error: 

> Reading in ppi data!
Error using sub2ind (line 43)
Out of range subscript.
Error in panda_network_with_GSE39612 (line 56)
TFCoop(sub2ind([NumTFs, NumTFs], i, j)) = weight;

when it's going to incorporate the PPI data to the analysis. I already removed the proteins that are not involved in either the expression (gene names) or the motif data (both TF and genes).  I wonder what could be the problem there?  Thanks!

**Comment by marouenbg** [comment]
Hi @Lyn16 ,
Thanks for reaching out. Would you have the PPI file in question?
Marouen

**Comment by Lyn16** [comment]
Hi Marouen,

I attached the .txt file in my question! Thanks!
Lyn

**Comment by marouenbg** [comment]
Hi @Lyn16 ,
I am going to need a little more time to look into this. Thank you for your patience!

**Comment by marouenbg** [comment]
Hi @Lyn16 ,
Can you please share your code, specifically how you call panda?
Also, I need the motif and gene expression files.
Thank you

**Comment by Lyn16** [comment]
Hi Marouen,

Here I attach the gene expression and the motif file:
[GSE39612_tumor.txt](https://github.com/netZoo/netZooM/files/7999186/GSE39612_tumor.txt)
[motif_GSE39612.txt](https://github.com/netZoo/netZooM/files/7999211/motif_GSE39612.txt)

I just followed the MATLAB guidance to set all the parameters and just used the function called panda_run to build regulatory network. Please let me know if there is anything else is needed. Thank you for your help.

Lyn

**Comment by marouenbg** [comment]
@Lyn16 ,
Can you share with me how you called panda_run  on these files?
Thank you

**Comment by marouenbg** [comment]
@Lyn16 it took me a while to get back to this because the CI on Matlab was not working. So the PPI matrix should be symmetrical, in other words the elements in the source column should be the same in the target column.

```
    TFNamesInit=unique(TF1);
    if ~isequal(TFNamesInit,unique(TF2))
        error('PPI data has missing information.')
    end
```
Looking at your file ppi_GSE39612.txt, the PPI network is not symmetric. Please feel free to reopen if you have any other question.
